export const TEST_SUCCES = "TEST_SUCCES";

export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAILURE = "USER_AUTH_FAILURE";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";

export const CREATE_OKTA_USER_SUCCESS = "CREATE_OKTA_USER_SUCCESS";

export const UPDATE_OKTA_USER_SUCCESS = "UPDATE_OKTA_USER_SUCCESS";

export const CREATE_OKTA_USER_FAILURE = "CREATE_OKTA_USER_FAILURE";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_INVITED_USER_DETAILS = "GET_INVITED_USER_DETAILS";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";

export const SEND_ACTIVATION_MAIL_SUCCESS = "SEND_ACTIVATION_MAIL_SUCCESS";

export const GET_BASIC_INFORMATION_SUCCESS = "GET_BASIC_INFORMATION_SUCCESS";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";
export const GET_DISTRICT_AND_BERRY_LIST_SUCCESS =
  "GET_DISTRICT_AND_BERRY_LIST_SUCCESS";
export const GET_DISTRICT_AND_COMPANY_LIST_SUCCESS =
  "GET_DISTRICT_AND_COMPANY_LIST_SUCCESS";
export const GET_COMPANY_AND_RANCH_LIST_SUCCESS =
  "GET_COMPANY_AND_RANCH_LIST_SUCCESS";

export const GET_ASSOCIATED_USERS_LIST_SUCCESS =
  "GET_ASSOCIATED_USERS_LIST_SUCCESS";
export const GET_USER_DETAILS_LIST_SUCCESS = "GET_USER_DETAILS_LIST_SUCCESS";
export const FILTER_USER_DETAILS_LIST = "FILTER_USER_DETAILS_LIST";

export const SET_PREFERRED_LANGUAGE = "SET_PREFERRED_LANGUAGE";
export const SET_FAQS_LANGUAGE = "SET_FAQS_LANGUAGE";

export const GET_REMINDERS_LIST_SUCCESS = "GET_REMINDERS_LIST_SUCCESS";

export const GET_MASS_ALERT_DISTRICT_LIST_SUCCESS = "GET_MASS_ALERT_DISTRICT_LIST_SUCCESS";
export const GET_MASS_ALERT_RANCH_LIST_SUCCESS = "GET_MASS_ALERT_RANCH_LIST_SUCCESS";
